### ISSUE TITLE
Tests failing on Windows

### ISSUE THREAD

**Issue by soapy1** [ContinuumIO/intake#233] opened 2019-01-16 20:48 UTC
I tried running the test suite on Windows in order to make a windows conda package however there was a good amount of failures ~40

[test.output.zip](https://github.com/ContinuumIO/intake/files/2765997/test.output.zip)

**Comment by martindurant** [comment] 2019-01-16 20:49
I would appreciate if you could investigate the root causes. I expect some simple path handling fixes probably go a long way to solving most.

**Comment by seibert** [comment] 2019-01-16 20:55
Scanning through the output, the most common issues seem to be:

* Strange behaviors with paths and regular expressions (where backslashes are being interpreted as escape characters?)  (See _munge_path)
* Assumptions in tests that the subprocess shell is bash, and therefore understands setting the environment by preceding the actual command with `VAR=VALUE`.

Fixing these two issues would likely take care of most of the failures.

**Comment by martindurant** [comment] 2019-01-16 20:59
The latter is simple, we should be passing an environment dictionary. The former may be annoying... we in general want to convert all paths that may be received into posix separators "/" at the earliest possibility, since those should work on win too.

**Comment by martindurant** [comment] 2019-01-24 18:32
Fixed by #234

**Closed by martindurant** 2019-01-24 18:32 UTC
